<template>
  <div class="main-container d-flex flex-column">
    <div class="nav-bar-container">
      <nav class="nav-bar d-flex justify-content-between align-items-center">
        <button class="menu-toggle-btn" @click="toggleSidebar">☰</button>
        <div class="logo">Logo Here</div>
        <div class="menu-items d-flex">
          <a href="#" class="menu-link">Logout</a>
        </div>
      </nav>
    </div>
    <div class="content-wrapper d-flex flex-grow-1">
      <div class="sidebar col-md-3 col-lg-2" :class="{ hidden: isSidebarHidden }">
        <a href="#" class="sidebar-link">Chat 1</a>
        <a href="#" class="sidebar-link">Chat 2</a>
        <a href="#" class="sidebar-link">Chat 3</a>
        <a href="#" class="sidebar-link">Chat 4</a>
        <a href="#" class="sidebar-link">Chat 5</a>
        <a href="#" class="sidebar-link">Chat 6</a>
        <a href="#" class="sidebar-link">Chat 7</a>
        <a href="#" class="sidebar-link">Chat 8</a>
      </div>
      <div class="content-container d-flex flex-column col-md-9 col-lg-10">
        <div class="text-generate-container flex-grow-1">
          <div class="user-chat">User: This is a message from the user.</div>
          <div class="ai-chat">AI: This is a message generated by the AI.</div>
          <div class="user-chat">User: Another user message here.</div>
          <div class="ai-chat">AI: Another AI response goes here.</div>
          <!-- Add more line -->
        </div>
        <div class="box-chat-container d-flex">
          <div class="col-2 col-xl-1 d-flex justify-content-center align-items-center">
            <button class="file-upload-btn">Upload</button>
          </div>
          <input class="box-chat col-5 col-xl-9" type="text" placeholder="Type your message here...">
          <div class="col-2 col-xl-1 d-flex justify-content-center align-items-center">
            <button class="send-btn">Send</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ChatboxPage',
  data() {
    return {
      isSidebarHidden: true,
    };
  },
  methods: {
    toggleSidebar() {
      this.isSidebarHidden = !this.isSidebarHidden;
    },
  },
};
</script>

<style>
/* General Styles */
.nav-bar-container {
  width: 100%;
  background-color: #007bff;
  color: white;
  padding: 10px 20px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
}

.nav-bar {
  max-width: 100vw;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  font-size: 1.5em;
  font-weight: bold;
  flex-grow: 1;
  text-align: center;
}

.menu-items {
  display: flex;
  gap: 15px;
}

.menu-link {
  color: white;
  text-decoration: none;
  font-size: 1em;
  transition: color 0.3s;
}

.menu-link:hover {
  color: #ffd700;
}

.menu-toggle-btn {
  background-color: transparent;
  color: white;
  border: none;
  font-size: 1.5em;
}

.main-container {
  width: 100vw;
  height: 100vh;
  background-color: #f8f9fa;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.content-wrapper {
  display: flex;
  flex-grow: 1;
  overflow: hidden;
}

.sidebar {
  background-color: #e9ecef;
  border-right: 1px solid #ced4da;
  padding: 10px;
  overflow-y: auto;
}

.sidebar-link {
  display: block;
  padding: 10px;
  text-decoration: none;
  color: #007bff;
  font-size: 1em;
  border-bottom: 1px solid #ced4da;
}

.sidebar-link:hover {
  background-color: #d6d8db;
  color: #0056b3;
}

.content-container {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}

.text-generate-container {
  flex-grow: 1;
  overflow-y: auto;
  padding: 10px;
  background-color: white;
  border: 1px solid #ced4da;
  border-radius: 5px;
}

.user-chat {
  text-align: right;
  border-right: 3px solid #007bff;
  padding: 10px;
  margin-bottom: 5px;
  background-color: #f1f1f1;
  border-radius: 5px;
}

.ai-chat {
  text-align: left;
  border-left: 3px solid #28a745;
  padding: 10px;
  margin-bottom: 5px;
  background-color: #f1f1f1;
  border-radius: 5px;
}

.box-chat-container {
  height: 10%;
  align-items: center;
  justify-content: space-evenly;
}

.box-chat {
  height: 70%;
  border-radius: 10px;
  border: 1px solid #ced4da;
  padding: 10px;
  font-size: 1em;
  outline: none;
}

.file-upload-btn, .send-btn {
  background-color: #007bff;
  color: white;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  font-size: 1em;
  cursor: pointer;
  transition: background-color 0.3s;
}

.file-upload-btn:hover, .send-btn:hover {
  background-color: #0056b3;
}

/* Sidebar Visibility */
.hidden {
  display: none !important;
}


/* Mobile Responsiveness */
@media (max-width: 768px) {
  .menu-toggle-btn {
    display: block;
  }

  .sidebar {
    display: hidden;
    max-height: 20vh;
    overflow-y: auto;
  }

  .sidebar.hidden {
    display: block;
  }

  .content-wrapper {
    flex-direction: column;
  }

  .content-container {
    flex-direction: column;
  }
}
</style>
